#pragma once

// Embedded font data as fallback when font files can't be loaded from disk
// This contains a minimal subset of the JetBrains Mono font for basic functionality

namespace EmbeddedFonts {
    // Minimal embedded font data (this would normally be generated by binary_to_compressed_c.cpp)
    // For now, we'll use a placeholder that indicates the font should be loaded from file
    extern const unsigned char* GetJetBrainsMonoData();
    extern int GetJetBrainsMonoDataSize();
    
    // Check if embedded font data is available
    bool IsEmbeddedFontAvailable();
}
