name: macOS Build and DMG
#note push all binary here
#https://github.com/rajumark/ADBKing
#token is PRIVATE_REPO_PAT
on:
  push:
    branches: [ main_dd ]
  workflow_dispatch:

jobs:
  build-dmg:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cmake sdl2 create-dmg

    - name: Build (Apple Silicon)
      env:
        PKG_CONFIG_PATH: /opt/homebrew/opt/sdl2/lib/pkgconfig
      run: |
        rm -rf build && mkdir build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_OSX_ARCHITECTURES=arm64 \
          -DCMAKE_EXE_LINKER_FLAGS="-L/opt/homebrew/opt/sdl2/lib" \
          -DCMAKE_CXX_LINK_FLAGS="-L/opt/homebrew/opt/sdl2/lib"
        make -j$(sysctl -n hw.ncpu)

    - name: Set version
      run: echo "VERSION=1.0.1" >> $GITHUB_ENV

    - name: Package binary into DMG
      run: |
        mkdir -p dist/imgui_folder
        cp build/imgui_app dist/imgui_folder/
        chmod +x dist/imgui_folder/imgui_app
        create-dmg \
          --volname "ADBKing" \
          --window-pos 200 120 \
          --window-size 500 300 \
          --icon-size 100 \
          --icon "imgui_app" 200 150 \
          "dist/ADBKing-${VERSION}.dmg" \
          "dist/imgui_folder"

    - name: Print DMG path and info
      run: |
        echo "✅ DMG successfully created:"
        echo "${{ github.workspace }}/dist/ADBKing-${VERSION}.dmg"
        echo "📦 Size:"
        ls -lh "${{ github.workspace }}/dist/ADBKing-${VERSION}.dmg" | awk '{print $5}'
        echo "📦 Binary architecture:"
        file dist/imgui_folder/imgui_app

    - name: Copy DMG to private repo MacM folder and push
      env:
        GIT_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git clone https://$GIT_TOKEN@github.com/rajumark/ADBKing.git
        mkdir -p ADBKing/MacM
        rm -rf ADBKing/MacM/*
        cp dist/ADBKing-${VERSION}.dmg ADBKing/MacM/
        cd ADBKing
        git add MacM/ADBKing-${VERSION}.dmg
        git commit -m "Add latest ADBKing-${VERSION}.dmg to MacM"
        git push origin main
